
package com.oracle.datago.model.rightnow;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "RequestErrorFault", targetNamespace = "urn:faults.ws.rightnow.com/v1")
public class RequestErrorFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private RequestErrorFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public RequestErrorFault(String message, RequestErrorFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public RequestErrorFault(String message, RequestErrorFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.oracle.datago.model.rightnow.RequestErrorFaultType
     */
    public RequestErrorFaultType getFaultInfo() {
        return faultInfo;
    }

}
