
package com.oracle.datago.model.rightnow;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "RightNowKnowledgePort", targetNamespace = "urn:wsdl.ws.rightnow.com/v1")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RightNowKnowledgePort {


    /**
     * 
     * @param userIPAddress
     * @param userAgent
     * @param requestHeader
     * @param appIdentifier
     * @param referrerURL
     * @return
     *     returns java.lang.String
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "StartInteraction", action = "StartInteraction")
    @WebResult(name = "SessionToken", targetNamespace = "urn:messages.ws.rightnow.com/v1")
    @RequestWrapper(localName = "StartInteraction", targetNamespace = "urn:messages.ws.rightnow.com/v1", className = "com.oracle.datago.model.rightnow.StartInteractionMsg")
    @ResponseWrapper(localName = "StartInteractionResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1", className = "com.oracle.datago.model.rightnow.StartInteractionResponseMsg")
    public String startInteraction(
        @WebParam(name = "AppIdentifier", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        String appIdentifier,
        @WebParam(name = "UserIPAddress", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        String userIPAddress,
        @WebParam(name = "ReferrerURL", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        String referrerURL,
        @WebParam(name = "UserAgent", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        String userAgent,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param contentSearch
     * @param sortOptions
     * @param sessionToken
     * @param limit
     * @param requestHeader
     * @return
     *     returns com.oracle.datago.model.rightnow.ContentListResponse
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "GetPopularContent", action = "GetPopularContent")
    @WebResult(name = "ContentListResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1")
    @RequestWrapper(localName = "GetPopularContent", targetNamespace = "urn:messages.ws.rightnow.com/v1", className = "com.oracle.datago.model.rightnow.GetPopularContentMsg")
    @ResponseWrapper(localName = "GetPopularContentResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1", className = "com.oracle.datago.model.rightnow.GetPopularContentResponseMsg")
    public ContentListResponse getPopularContent(
        @WebParam(name = "SessionToken", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        String sessionToken,
        @WebParam(name = "ContentSearch", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        ContentSearch contentSearch,
        @WebParam(name = "Limit", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        Integer limit,
        @WebParam(name = "SortOptions", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        ContentSortOptions sortOptions,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param contentSearch
     * @param subject
     * @param sessionToken
     * @param limit
     * @param requestHeader
     * @param body
     * @return
     *     returns com.oracle.datago.model.rightnow.ContentListResponse
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "GetSmartAssistantSearch", action = "GetSmartAssistantSearch")
    @WebResult(name = "ContentListResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1")
    @RequestWrapper(localName = "GetSmartAssistantSearch", targetNamespace = "urn:messages.ws.rightnow.com/v1", className = "com.oracle.datago.model.rightnow.GetSmartAssistantSearchMsg")
    @ResponseWrapper(localName = "GetSmartAssistantSearchResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1", className = "com.oracle.datago.model.rightnow.GetSmartAssistantSearchResponseMsg")
    public ContentListResponse getSmartAssistantSearch(
        @WebParam(name = "SessionToken", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        String sessionToken,
        @WebParam(name = "Body", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        String body,
        @WebParam(name = "Subject", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        String subject,
        @WebParam(name = "ContentSearch", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        ContentSearch contentSearch,
        @WebParam(name = "Limit", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        Integer limit,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param smartAssistantSearch
     * @param requestHeader
     * @return
     *     returns com.oracle.datago.model.rightnow.ContentListResponse
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "GetSmartAssistantSearchExtended", action = "GetSmartAssistantSearchExtended")
    @WebResult(name = "ContentListResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1")
    @RequestWrapper(localName = "GetSmartAssistantSearchExtended", targetNamespace = "urn:messages.ws.rightnow.com/v1", className = "com.oracle.datago.model.rightnow.GetSmartAssistantSearchExtendedMsg")
    @ResponseWrapper(localName = "GetSmartAssistantSearchExtendedResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1", className = "com.oracle.datago.model.rightnow.GetSmartAssistantSearchExtendedResponseMsg")
    public ContentListResponse getSmartAssistantSearchExtended(
        @WebParam(name = "SmartAssistantSearch", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        SmartAssistantSearch smartAssistantSearch,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param sessionToken
     * @param limit
     * @param requestHeader
     * @param content
     * @return
     *     returns com.oracle.datago.model.rightnow.ContentListResponse
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "GetRecommendedContent", action = "GetRecommendedContent")
    @WebResult(name = "ContentListResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1")
    @RequestWrapper(localName = "GetRecommendedContent", targetNamespace = "urn:messages.ws.rightnow.com/v1", className = "com.oracle.datago.model.rightnow.GetRecommendedContentMsg")
    @ResponseWrapper(localName = "GetRecommendedContentResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1", className = "com.oracle.datago.model.rightnow.GetRecommendedContentResponseMsg")
    public ContentListResponse getRecommendedContent(
        @WebParam(name = "SessionToken", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        String sessionToken,
        @WebParam(name = "Content", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        Content content,
        @WebParam(name = "Limit", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        Integer limit,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param includeSpellingSuggestions
     * @param searchTerms
     * @param sortOptions
     * @param origin
     * @param sessionToken
     * @param limit
     * @param start
     * @param requestHeader
     * @param filters
     * @param includeRelatedSearches
     * @param securityOptions
     * @return
     *     returns com.oracle.datago.model.rightnow.SearchResponse
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "SearchContent", action = "SearchContent")
    @WebResult(name = "SearchResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1")
    @RequestWrapper(localName = "SearchContent", targetNamespace = "urn:messages.ws.rightnow.com/v1", className = "com.oracle.datago.model.rightnow.SearchContentMsg")
    @ResponseWrapper(localName = "SearchContentResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1", className = "com.oracle.datago.model.rightnow.SearchContentResponseMsg")
    public SearchResponse searchContent(
        @WebParam(name = "SessionToken", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        String sessionToken,
        @WebParam(name = "SearchTerms", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        String searchTerms,
        @WebParam(name = "Filters", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        ContentFilterList filters,
        @WebParam(name = "IncludeRelatedSearches", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        Boolean includeRelatedSearches,
        @WebParam(name = "IncludeSpellingSuggestions", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        Boolean includeSpellingSuggestions,
        @WebParam(name = "Limit", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        Integer limit,
        @WebParam(name = "Origin", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        ContentSearchOrigin origin,
        @WebParam(name = "SecurityOptions", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        ContentSecurityOptions securityOptions,
        @WebParam(name = "SortOptions", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        ContentSortOptions sortOptions,
        @WebParam(name = "Start", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        Integer start,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param requestHeader
     * @param contentGroupedSearch
     * @return
     *     returns com.oracle.datago.model.rightnow.GroupedSearchResponse
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "SearchGroupedContent", action = "SearchGroupedContent")
    @WebResult(name = "GroupedSearchResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1")
    @RequestWrapper(localName = "SearchGroupedContent", targetNamespace = "urn:messages.ws.rightnow.com/v1", className = "com.oracle.datago.model.rightnow.SearchGroupedContentMsg")
    @ResponseWrapper(localName = "SearchGroupedContentResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1", className = "com.oracle.datago.model.rightnow.SearchGroupedContentResponseMsg")
    public GroupedSearchResponse searchGroupedContent(
        @WebParam(name = "ContentGroupedSearch", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        ContentGroupedSearch contentGroupedSearch,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param contentTemplate
     * @param viewOrigin
     * @param sessionToken
     * @param requestHeader
     * @param securityOptions
     * @return
     *     returns com.oracle.datago.model.rightnow.Content
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "GetContent", action = "GetContent")
    @WebResult(name = "Content", targetNamespace = "urn:messages.ws.rightnow.com/v1")
    @RequestWrapper(localName = "GetContent", targetNamespace = "urn:messages.ws.rightnow.com/v1", className = "com.oracle.datago.model.rightnow.GetContentMsg")
    @ResponseWrapper(localName = "GetContentResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1", className = "com.oracle.datago.model.rightnow.GetContentResponseMsg")
    public Content getContent(
        @WebParam(name = "SessionToken", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        String sessionToken,
        @WebParam(name = "ContentTemplate", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        Content contentTemplate,
        @WebParam(name = "SecurityOptions", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        ContentSecurityOptions securityOptions,
        @WebParam(name = "ViewOrigin", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        ContentViewOrigin viewOrigin,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param viewOrigin
     * @param sessionToken
     * @param requestHeader
     * @param content
     * @return
     *     returns com.oracle.datago.model.rightnow.ContentRequestStatus
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "MarkContentAsViewed", action = "MarkContentAsViewed")
    @WebResult(name = "ContentRequestStatus", targetNamespace = "urn:messages.ws.rightnow.com/v1")
    @RequestWrapper(localName = "MarkContentAsViewed", targetNamespace = "urn:messages.ws.rightnow.com/v1", className = "com.oracle.datago.model.rightnow.MarkContentAsViewedMsg")
    @ResponseWrapper(localName = "MarkContentAsViewedResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1", className = "com.oracle.datago.model.rightnow.MarkContentAsViewedResponseMsg")
    public ContentRequestStatus markContentAsViewed(
        @WebParam(name = "SessionToken", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        String sessionToken,
        @WebParam(name = "Content", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        Content content,
        @WebParam(name = "ViewOrigin", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        ContentViewOrigin viewOrigin,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param rate
     * @param sessionToken
     * @param scale
     * @param requestHeader
     * @param content
     * @return
     *     returns com.oracle.datago.model.rightnow.ContentRequestStatus
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "RateContent", action = "RateContent")
    @WebResult(name = "ContentRequestStatus", targetNamespace = "urn:messages.ws.rightnow.com/v1")
    @RequestWrapper(localName = "RateContent", targetNamespace = "urn:messages.ws.rightnow.com/v1", className = "com.oracle.datago.model.rightnow.RateContentMsg")
    @ResponseWrapper(localName = "RateContentResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1", className = "com.oracle.datago.model.rightnow.RateContentResponseMsg")
    public ContentRequestStatus rateContent(
        @WebParam(name = "SessionToken", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        String sessionToken,
        @WebParam(name = "Content", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        Content content,
        @WebParam(name = "Rate", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        ContentRate rate,
        @WebParam(name = "Scale", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        ContentRate scale,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param fieldName
     * @param requestHeader
     * @param packageName
     * @return
     *     returns java.util.List<com.oracle.datago.model.rightnow.NamedID>
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "GetValuesForNamedID", action = "GetValuesForNamedID")
    @WebResult(name = "Entry", targetNamespace = "urn:messages.ws.rightnow.com/v1")
    @RequestWrapper(localName = "GetValuesForNamedID", targetNamespace = "urn:messages.ws.rightnow.com/v1", className = "com.oracle.datago.model.rightnow.GetValuesForNamedIDMsg")
    @ResponseWrapper(localName = "GetValuesForNamedIDResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1", className = "com.oracle.datago.model.rightnow.GetValuesForNamedIDResponseMsg")
    public List<NamedID> getValuesForNamedID(
        @WebParam(name = "PackageName", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        String packageName,
        @WebParam(name = "FieldName", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        String fieldName,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param contentSearch
     * @param keyValueItems
     * @param sessionToken
     * @param limit
     * @param requestHeader
     * @return
     *     returns com.oracle.datago.model.rightnow.SmartAssistantSuggestionsResponse
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "GetSmartAssistantSuggestions", action = "GetSmartAssistantSuggestions")
    @WebResult(name = "SmartAssistantSuggestionsResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1")
    @RequestWrapper(localName = "GetSmartAssistantSuggestions", targetNamespace = "urn:messages.ws.rightnow.com/v1", className = "com.oracle.datago.model.rightnow.GetSmartAssistantSuggestionsMsg")
    @ResponseWrapper(localName = "GetSmartAssistantSuggestionsResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1", className = "com.oracle.datago.model.rightnow.GetSmartAssistantSuggestionsResponseMsg")
    public SmartAssistantSuggestionsResponse getSmartAssistantSuggestions(
        @WebParam(name = "SessionToken", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        String sessionToken,
        @WebParam(name = "ContentSearch", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        ContentSearch contentSearch,
        @WebParam(name = "KeyValueItems", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        KeyValueItemList keyValueItems,
        @WebParam(name = "Limit", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        Integer limit,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param smartAssistantSuggestions
     * @param requestHeader
     * @return
     *     returns com.oracle.datago.model.rightnow.SmartAssistantSuggestionsResponse
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "GetSmartAssistantSuggestionsExtended", action = "GetSmartAssistantSuggestionsExtended")
    @WebResult(name = "SmartAssistantSuggestionsResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1")
    @RequestWrapper(localName = "GetSmartAssistantSuggestionsExtended", targetNamespace = "urn:messages.ws.rightnow.com/v1", className = "com.oracle.datago.model.rightnow.GetSmartAssistantSuggestionsExtendedMsg")
    @ResponseWrapper(localName = "GetSmartAssistantSuggestionsExtendedResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1", className = "com.oracle.datago.model.rightnow.GetSmartAssistantSuggestionsExtendedResponseMsg")
    public SmartAssistantSuggestionsResponse getSmartAssistantSuggestionsExtended(
        @WebParam(name = "SmartAssistantSuggestions", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        SmartAssistantSuggestions smartAssistantSuggestions,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

    /**
     * 
     * @param smartAssistantToken
     * @param sessionToken
     * @param requestHeader
     * @param escalationObject
     * @param resolution
     * @return
     *     returns com.oracle.datago.model.rightnow.ContentRequestStatus
     * @throws UnexpectedErrorFault
     * @throws ServerErrorFault
     * @throws RequestErrorFault
     */
    @WebMethod(operationName = "RegisterSmartAssistantResolution", action = "RegisterSmartAssistantResolution")
    @WebResult(name = "ContentRequestStatus", targetNamespace = "urn:messages.ws.rightnow.com/v1")
    @RequestWrapper(localName = "RegisterSmartAssistantResolution", targetNamespace = "urn:messages.ws.rightnow.com/v1", className = "com.oracle.datago.model.rightnow.RegisterSmartAssistantResolutionMsg")
    @ResponseWrapper(localName = "RegisterSmartAssistantResolutionResponse", targetNamespace = "urn:messages.ws.rightnow.com/v1", className = "com.oracle.datago.model.rightnow.RegisterSmartAssistantResolutionResponseMsg")
    public ContentRequestStatus registerSmartAssistantResolution(
        @WebParam(name = "SessionToken", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        String sessionToken,
        @WebParam(name = "SmartAssistantToken", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        String smartAssistantToken,
        @WebParam(name = "Resolution", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        SmartAssistantResolution resolution,
        @WebParam(name = "EscalationObject", targetNamespace = "urn:messages.ws.rightnow.com/v1")
        RNObject escalationObject,
        @WebParam(name = "ClientInfoHeader", targetNamespace = "urn:messages.ws.rightnow.com/v1", header = true, partName = "request_header")
        ClientInfoHeader requestHeader)
        throws RequestErrorFault, ServerErrorFault, UnexpectedErrorFault
    ;

}
