
package com.oracle.datago.model.rightnow;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ServerErrorFault", targetNamespace = "urn:faults.ws.rightnow.com/v1")
public class ServerErrorFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ServerErrorFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ServerErrorFault(String message, ServerErrorFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ServerErrorFault(String message, ServerErrorFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.oracle.datago.model.rightnow.ServerErrorFaultType
     */
    public ServerErrorFaultType getFaultInfo() {
        return faultInfo;
    }

}
