
package com.oracle.datago.model.rightnow;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "UnexpectedErrorFault", targetNamespace = "urn:faults.ws.rightnow.com/v1")
public class UnexpectedErrorFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UnexpectedErrorFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UnexpectedErrorFault(String message, UnexpectedErrorFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public UnexpectedErrorFault(String message, UnexpectedErrorFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.oracle.datago.model.rightnow.UnexpectedErrorFaultType
     */
    public UnexpectedErrorFaultType getFaultInfo() {
        return faultInfo;
    }

}
